"""Cria tabela produto_favorito

Revision ID: 513293c1cf12
Revises: db3d0e14fb9a
Create Date: 2025-09-09 02:53:41.572709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '513293c1cf12'
down_revision: Union[str, Sequence[str], None] = 'db3d0e14fb9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto_favorito',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'produto_id', name='_cliente_produto_uc')
    )
    op.create_index(op.f('ix_produto_favorito_produto_id'), 'produto_favorito', ['produto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produto_favorito_produto_id'), table_name='produto_favorito')
    op.drop_table('produto_favorito')
    # ### end Alembic commands ###
