"""Adiciona exclusao logica a clientes

Revision ID: c2149af5890d
Revises: 513293c1cf12
Create Date: 2025-09-10 18:40:25.181583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2149af5890d'
down_revision: Union[str, Sequence[str], None] = '513293c1cf12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_cliente_email'), table_name='cliente')
    op.create_index(op.f('ix_cliente_email'), 'cliente', ['email'], unique=False)
    op.create_index('idx_cliente_email_unico_ativo', 'cliente', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cliente_email_unico_ativo', table_name='cliente', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_cliente_email'), table_name='cliente')
    op.create_index(op.f('ix_cliente_email'), 'cliente', ['email'], unique=True)
    op.drop_column('cliente', 'deleted_at')
    # ### end Alembic commands ###
