"""Adiciona campo hash_senha ao cliente

Revision ID: db3d0e14fb9a
Revises: 7dc1340894ff
Create Date: 2025-09-08 11:50:46.086693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3d0e14fb9a'
down_revision: Union[str, Sequence[str], None] = '7dc1340894ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('hash_senha', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cliente', 'hash_senha')
    # ### end Alembic commands ###
